### ISSUE TITLE
FPGA part speed grade on U45N

### ISSUE THREAD

**Issue by JakaBac** [Xilinx/open-nic-shell#68]
In case of U45N OpenNIC is built for -2LV part. With that part Vivado fails to close timing (WNS -0.993 and TNS -2025.445). I didn't try IDR but I suspect that will also struggle a lot.

I have a SN1022 and I can see that Vccint is 0.85V and not 0.72V. That would imply that the design can be built for -2L part. I haven't tried that yet, but I suspect that it will meet timing even without IDR. From what I know SN1022 and U45N are very closely related.

An owner of an actual U45N also commented on AMD forum that Vccint on his board is 0.85V
[AU45N QSFP Port numbering error and part number](https://adaptivesupport.amd.com/s/question/0D54U00008KLFaFSAX/au45n-qsfp-port-numbering-error-and-part-number?language=en_US)

But then again I also know somebody who owns a SN1022 and his card has 0.72V Vccint.

Is it possible that first versions of SN1022 had regulators configured for 0.72V and that this was later changed to 0.85V which is still the case on U45N?

**Comment by JakaBac** [comment]
I tried to build OpenNIC for -2L part and it easily meets timing. If all U45N cards have VCCINT regulators configured for 0.85V then it would make sense to make -2L as the default part?

**Comment by Jinbei43** [comment]
Hi @JakaBac , I have U45N cards and the same problem as you. I tried IDR optimization and it still failed. I would like to know if after you build and flash the shell with -2L part, can you use the card function normally when running with the ONIC driver? (I mean basic Ethernet operation, TX/RX)

<img width="570" alt="Image" src="https://github.com/user-attachments/assets/fa4f9dd7-f4b3-445d-b7df-bf079412d288" />

**Comment by JakaBac** [comment]
In my case IDR meets timing. Which version of Vivado are you using?
Building shell with -2L part without IDR meets timing and the board works. But I did limited testing. Just be sure that the regulators on your board are configured for Vccint is 0.85V. The regulators are OTP and probably configuration is fixed during manufacturing.

However keep in mind that the only officially supported is using IDR and -2LV part.

**Comment by Jinbei43** [comment]
I currently use Vivado 2024.2 and board -2LV part from default OpenNIC shell code and AMD technical document. And when I built this default shell and used IDR (even ML IDR) like you said, it still failed as shown in the previous comment.

I tried to build shell with -2L part (renamed in board_settings section inside /script directory), but it also gives a lot of warnings about timing. 
<img width="772" alt="Image" src="https://github.com/user-attachments/assets/aaa9a68c-ff45-4d45-bc19-eb74091240ee" />

I would like to know if I need to modify the code in addition to the default provided. Because I tried to fix this problem from each of the issues answers in this repo but it still doesn't work. Or if possible, can you send me your shell code and mcs file to build and flash on my U45N? 

Lastly: I'm new about this Xilinx FPGA, how can I check that my U45N board regulators are configured for VCCINT at 0.85V?

**Comment by JakaBac** [comment]
I built the shell using 2022.1 or 2023.1 I don't remember which one. I know that 2023.2 has some issues. On that version IDR run closed timing.

You can check Vccint by using SysMon in Vivado over JTAG
Please see https://docs.amd.com/r/en-US/ug908-vivado-programming-debugging/System-Monitor

Keep in mind that you need to have the ADK2 debug interface or some kind of adapter to connect to the custom card edge debug port on the U45N.

The Debug port pinout is publicly documented in:
https://docs.amd.com/r/en-US/ug1538-alveo-debug/Debug-Connector

I did very little testing of AMD OpenNIC and did not look into the warnings that are emitted during synthesis. From the screenshot it is not apparent what exactly is causing the warnings. 
I used the unmodified shell code from this repository to build the bitstream, when I was testing this. I don't have the mcs file anymore, I would need to rebuild the bitstream and I also upgraded Vivado to newer version since that time.

**Comment by Jinbei43** [comment]
Thank you so much for your valuable advice! It worked when I changed Vivado's version from 2024.2 to 2022.1 with -2LV part and IDR.

However, when I loaded ONIC driver and run simple connection between both ports in the same card via QSFP28 cable, there is no response whatsoever. But after I changed my U45N card to connect to another U45N card, it was able to communicate with each other. (I tried to find the cause from the [ONIC driver's issues](https://github.com/Xilinx/open-nic-driver/issues), but I couldn't find it. But it's okay because at least my card is usable now.)

But I ran into a new problem, card performance. When I ping both cards, the latency is around tens of thousands milliseconds. And throughput when I use iPerf3 is around 5 Gb/s (I know it won't reach 100 Gb/s line-rate because of in-host bottleneck, but it shouldn't be that slow.) I don't know if this is a driver or shell issue because after I checked SysMon via ADK2, VCCINT is around 0.85V. Maybe I should raise this problem in ONIC driver's issue.

<img width="1163" height="475" alt="Image" src="https://github.com/user-attachments/assets/37473a99-36d6-4604-9039-dc607cbb4a6d" />
Latency result when I ping both cards together.
<img width="954" height="479" alt="Image" src="https://github.com/user-attachments/assets/94de82f7-3527-45a7-b8b0-8217473c5bbd" />
SysMon with VCCINT value (bottom left).

**Comment by rahul7rajdn** [comment]
<img width="1919" height="865" alt="Image" src="https://github.com/user-attachments/assets/91830eac-c372-4b19-a886-137126403b4d" />


I am using Vivado 2022.1 and Implementation failed timing.

So, I started IDR as suggested. But IDR does keeps running forever and does not terminate as shown in the screenshot.

 [open-nic-shell]$ cat  script/board_settings/au45n.tcl 
set part xcu26-vsva1365-2LV-e
set board_part ""
set zynq_family 0

**Comment by Jinbei43** [comment]
Please check you Vivado IDR, because it's fine for me by it usually takes no more than 24 hours to run. But like I described in the previous comment, -2LV part number for my case still has problems when I flashed to my U45N.

I suggest to change part number to -2L + IDR for better performance and 5 RQA score.

(I tried to build -2L without IDR like JakaBac's solution, but I received some warning messages as a picture below)
<img width="966" height="238" alt="Image" src="https://github.com/user-attachments/assets/0dde14a8-9474-4b38-a845-fc7ddc7a2a28" />

**Comment by rahul7rajdn** [comment]
set part xcu26-vsva1365-2LV-e

set part -2LV


Do you mean to change the part number to just "-2LV" as above...?

I was using the part what was already listed.

**Comment by Jinbei43** [comment]
For my case now, I changed script file to this

set part xcu26-vsva1365-2L-e
set board_part ""
set zynq_family 0

**Comment by JakaBac** [comment]
You have to specify the full part name with set_part. In case of -2L part this is xcu26-vsva1365-2L-e.
But before doing that verify, that your board is configured to use 0.85V for Vccint (you can do that with SysMon). If you will see 0.72V for Vccint, then using -2L part will definitely not work (sure Vivado will build the bitstream just fine, but the design will definitely fail in HW).

Please keep in mind that Xilinx/AMD only supports using xcu26-vsva1365-2LV-e part.

Also keep in mind that IDR run can take insanely long time on a slow CPU, especially if Vivado is struggling to meet timing with the design.
